### ISSUE TITLE
Add Ability to attach documents to transactions

### ISSUE THREAD

**Issue by Stevo-S** [Stevo-S/LoanManager#10]
I was thinking it might be cool if we could allow attachments when a transaction is recorded.
So for example, a scanned financial document if the transaction is a payment.

**Comment by Gakere** [comment]
I second that. It'll be a ++ on the appeal and usability of the app.

On Thu, Mar 3, 2016 at 7:55 PM, Stevo-S <notifications@github.com> wrote:

> I was thinking it might be cool if we could allow attachments when a
> transaction is recorded.
> So for example, a scanned financial document if the transaction is a
> payment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stevo-S/LoanManager/issues/10>.
>



-- 
Warm Regards,
Sam

*“Luck Is What Happens When Preparation Meets Opportunity"*

**Comment by Stevo-S** [comment]
Pull request #15 fixed this so I am closing it now.

We may have to look into possibly restricting the number of attachments a user can upload though.
